apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-service
spec:
  selector:
    matchLabels:
      app: metric-service
  replicas: 2
  template:
    metadata:
      labels:
        app: metric-service
    spec:
      containers:
        - name: metric-service
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          env:
          - name: spring_profiles_active
            value: qa
          ports:
            - containerPort: 9194